### ISSUE TITLE
lib/XML/Spice.pm does not match LICENSE

### ISSUE THREAD

**Issue by ppisar** [robn/XML-Spice#1]
lib/XML/Spice.pm reads:

~~~~
This module is free software, you can redistribute it and/or modify it under
the same terms as Perl itself.
~~~~

and that means (GPL+ or Artistic 1) <http://dev.perl.org/licenses/>. But LICENSE and README file declares Artistic 2.0. I guess you want to change one of them.

**Comment by robn** [comment]
Ahh, good catch. I actually accidentally fixed this in the repo last year, but didn't cut a release because there was no changes. There still isn't, but I've pushed 0.05 to CPAN anyway just to make sort this out.
